# Generated by Django 6.0.2 on 2026-02-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailattachment',
            options={'ordering': ['inbound_email_id', 'id'], 'verbose_name': 'Privitak emaila', 'verbose_name_plural': 'Privitci emaila'},
        ),
        migrations.AlterModelOptions(
            name='inboundemail',
            options={'ordering': ['-received_at', '-id'], 'verbose_name': 'Dolazni email', 'verbose_name_plural': 'Dolazni emailovi'},
        ),
        migrations.AlterModelOptions(
            name='outboundemail',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Odlazni email', 'verbose_name_plural': 'Odlazni emailovi'},
        ),
        migrations.AlterModelOptions(
            name='parseerror',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Greska parsiranja', 'verbose_name_plural': 'Greske parsiranja'},
        ),
        migrations.AlterField(
            model_name='inboundemail',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Na cekanju'), ('parsed', 'Parsirano'), ('partial', 'Djelomicno'), ('failed', 'Neuspjelo')], default='pending', max_length=16),
        ),
    ]
