# Generated by Django 6.0.2 on 2026-02-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_emailattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundemail',
            name='parsed_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
