# Generated by Django 6.0.2 on 2026-02-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['reservation_id', '-is_primary', 'last_name', 'first_name'], 'verbose_name': 'Gost', 'verbose_name_plural': 'Gosti'},
        ),
        migrations.AlterModelOptions(
            name='iddocument',
            options={'ordering': ['-created_at', 'id'], 'verbose_name': 'Identifikacijski dokument', 'verbose_name_plural': 'Identifikacijski dokumenti'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['check_in_date', 'id'], 'verbose_name': 'Rezervacija', 'verbose_name_plural': 'Rezervacije'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('expected', 'Ocekuje dolazak'), ('checked_in', 'Prijavljen'), ('checked_out', 'Odjavljen'), ('canceled', 'Otkazan')], default='expected', max_length=32),
        ),
    ]
