# Generated by Django 6.0.2 on 2026-02-13 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_guest_options_alter_iddocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('passporteye', 'PassportEye'), ('microblink', 'Microblink')], max_length=32)),
                ('status', models.CharField(choices=[('ok', 'Uspjesno'), ('failed', 'Neuspjesno')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('suggested_fields', models.JSONField(blank=True, default=dict)),
                ('corrected_fields', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocr_scan_logs', to=settings.AUTH_USER_MODEL)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_scan_logs', to='reception.guest')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_scan_logs', to='reception.reservation')),
            ],
            options={
                'verbose_name': 'OCR scan log',
                'verbose_name_plural': 'OCR scan logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
