# Generated by Django 6.0.2 on 2026-02-13

from django.db import migrations, models


def remap_passporteye_to_microblink(apps, schema_editor):
    OcrScanLog = apps.get_model("reception", "OcrScanLog")
    OcrScanLog.objects.filter(provider="passporteye").update(provider="microblink")


class Migration(migrations.Migration):
    dependencies = [
        ("reception", "0003_ocrscanlog"),
    ]

    operations = [
        migrations.RunPython(remap_passporteye_to_microblink, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ocrscanlog",
            name="provider",
            field=models.CharField(choices=[("microblink", "Microblink")], max_length=32),
        ),
    ]
