# Generated by Django 6.0.2 on 2026-02-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0004_remove_passporteye_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='additional_personal_id_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_additional_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_country_iso2',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_country_iso3',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_country_numeric',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='guest',
            name='document_type',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guest',
            name='issuing_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guest',
            name='mrz_raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='mrz_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='personal_id_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='guest',
            name='sex',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
