# Generated by Django 6.0.2 on 2026-02-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_guest_additional_personal_id_number_guest_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
