# Generated by Django 6.0.2 on 2026-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0018_booking_extranet_needs_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evisitorsubmission',
            name='status',
            field=models.CharField(choices=[('not_sent', 'Nije poslano'), ('pending', 'U tijeku'), ('sent', 'Poslano'), ('checked_out', 'Odjavljeno'), ('failed', 'Neuspjesno')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='import_source',
            field=models.CharField(blank=True, choices=[('booking_xls', 'Booking XLS'), ('booking_email', 'Booking email'), ('booking_ical', 'Booking iCal')], max_length=32),
        ),
    ]
