# Generated by Django 6.0.2 on 2026-02-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('subtitle_i18n', models.JSONField(blank=True, default=dict)),
                ('amenities_i18n', models.JSONField(blank=True, default=dict)),
                ('size_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('match_aliases', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vrsta sobe',
                'verbose_name_plural': 'Vrste soba',
                'ordering': ['code'],
            },
        ),
    ]
