# Generated by Django 6.0.2 on 2026-02-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='beds_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='highlights_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='views_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
