# Generated by Django 6.0.2 on 2026-02-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomTypePhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="room_types/photos/%Y/%m/%d/")),
                ("caption_i18n", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="rooms.roomtype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fotografija vrste sobe",
                "verbose_name_plural": "Fotografije vrste sobe",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]

