# Generated by Django 6.0.2 on 2026-02-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_roomtypephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='default', max_length=64, unique=True)),
                ('name_i18n', models.JSONField(blank=True, default=dict)),
                ('about_i18n', models.JSONField(blank=True, default=dict)),
                ('company_info_i18n', models.JSONField(blank=True, default=dict)),
                ('neighborhood_i18n', models.JSONField(blank=True, default=dict)),
                ('most_popular_facilities_i18n', models.JSONField(blank=True, default=dict)),
                ('address_i18n', models.JSONField(blank=True, default=dict)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('google_maps_url', models.URLField(blank=True, default='')),
                ('google_maps_embed_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekt',
                'ordering': ['code'],
            },
        ),
    ]
