# Generated by Django 6.0.2 on 2026-02-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_propertyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='surroundings_i18n',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
