# Generated by Django 6.0.2 on 2026-02-16 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_propertyinfo_surroundings_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyinfo',
            name='google_maps_embed_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='propertyinfo',
            name='google_maps_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
