# Generated by Django 6.0.2 on 2026-02-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_alter_propertyinfo_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='', help_text='WhatsApp broj u E.164 formatu, npr. +385998388513', max_length=32),
        ),
    ]
