# Generated by Django 6.0.2 on 2026-02-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_propertyinfo_whatsapp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypephoto',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Oznaci fotografiju kao glavnu.'),
        ),
    ]
