# Generated by Django 6.0.2 on 2026-02-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_roomtypephoto_is_primary'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roomtypephoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('room_type',), name='unique_primary_photo_per_room_type'),
        ),
    ]
