# Generated by Django 6.0.2 on 2026-02-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_roomtypephoto_unique_primary_photo_per_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyinfo',
            name='google_analytics_measurement_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics 4 Measurement ID, npr. G-PXHBKJD09B', max_length=32),
        ),
    ]
