# Generated by Django 6.0.2 on 2026-02-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_propertyinfo_google_analytics_measurement_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypePricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('base_price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plans', to='rooms.roomtype')),
            ],
            options={
                'verbose_name': 'Cjenik vrste sobe',
                'verbose_name_plural': 'Cjenici vrste sobe',
                'ordering': ['room_type__code', '-is_default', 'code'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypePricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('rule_type', models.CharField(choices=[('season', 'Sezona'), ('month', 'Mjesec'), ('week', 'Tjedan'), ('day', 'Dan')], max_length=16)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_stay_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iso_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ponedjeljak'), (2, 'Utorak'), (3, 'Srijeda'), (4, 'Četvrtak'), (5, 'Petak'), (6, 'Subota'), (7, 'Nedjelja')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='rooms.roomtypepricingplan')),
            ],
            options={
                'verbose_name': 'Pravilo cijene',
                'verbose_name_plural': 'Pravila cijena',
                'ordering': ['pricing_plan__room_type__code', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='roomtypepricingplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('room_type',), name='unique_default_pricing_plan_per_room_type'),
        ),
        migrations.AddConstraint(
            model_name='roomtypepricingplan',
            constraint=models.UniqueConstraint(fields=('room_type', 'code'), name='unique_pricing_plan_code_per_room_type'),
        ),
    ]
