# Generated by Django 6.0.2 on 2026-02-16

import django.db.models.deletion
from django.db import migrations, models


def _copy_plans_to_rooms(apps, schema_editor):
    Plan = apps.get_model("rooms", "RoomTypePricingPlan")
    Rule = apps.get_model("rooms", "RoomTypePricingRule")
    Room = apps.get_model("rooms", "Room")

    rule_fields = [
        "name",
        "rule_type",
        "price_per_night",
        "min_stay_nights",
        "valid_from",
        "valid_to",
        "month",
        "iso_week",
        "weekday",
        "specific_date",
        "sort_order",
        "is_active",
    ]

    for plan in Plan.objects.all().order_by("id"):
        room_ids = list(Room.objects.filter(room_type_id=plan.room_type_id).order_by("id").values_list("id", flat=True))
        if not room_ids:
            continue

        base_rules = list(Rule.objects.filter(pricing_plan_id=plan.id).values(*rule_fields))

        # Reuse existing plan row for the first room.
        plan.room_id = room_ids[0]
        plan.save(update_fields=["room"])

        # Clone plan+rules for additional rooms of same room_type.
        for room_id in room_ids[1:]:
            cloned = Plan.objects.create(
                room_type_id=plan.room_type_id,
                room_id=room_id,
                code=plan.code,
                name=plan.name,
                currency=plan.currency,
                base_price_per_night=plan.base_price_per_night,
                valid_from=plan.valid_from,
                valid_to=plan.valid_to,
                is_default=plan.is_default,
                is_active=plan.is_active,
            )
            for rule_data in base_rules:
                Rule.objects.create(pricing_plan_id=cloned.id, **rule_data)

    # Drop plans that cannot be mapped to any physical room.
    Plan.objects.filter(room_id__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0012_roomtypepricingplan_roomtypepricingrule_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtypepricingplan",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_plans",
                to="rooms.room",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="roomtypepricingplan",
            name="unique_default_pricing_plan_per_room_type",
        ),
        migrations.RemoveConstraint(
            model_name="roomtypepricingplan",
            name="unique_pricing_plan_code_per_room_type",
        ),
        migrations.RunPython(_copy_plans_to_rooms, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="roomtypepricingplan",
            name="room_type",
        ),
        migrations.AlterField(
            model_name="roomtypepricingplan",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_plans",
                to="rooms.room",
            ),
        ),
        migrations.AlterModelOptions(
            name="roomtypepricingplan",
            options={
                "ordering": ["room__code", "-is_default", "code"],
                "verbose_name": "Cjenik sobe",
                "verbose_name_plural": "Cjenici soba",
            },
        ),
        migrations.AlterModelOptions(
            name="roomtypepricingrule",
            options={
                "ordering": ["pricing_plan__room__code", "sort_order", "id"],
                "verbose_name": "Pravilo cijene",
                "verbose_name_plural": "Pravila cijena",
            },
        ),
        migrations.AddConstraint(
            model_name="roomtypepricingplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("room",),
                name="unique_default_pricing_plan_per_room",
            ),
        ),
        migrations.AddConstraint(
            model_name="roomtypepricingplan",
            constraint=models.UniqueConstraint(
                fields=("room", "code"),
                name="unique_pricing_plan_code_per_room",
            ),
        ),
    ]
