# Generated by Django 6.0.2 on 2026-02-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_room_pricing_per_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypepricingrule',
            name='adults_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ako je postavljeno, pravilo vrijedi samo za točan broj odraslih.', null=True),
        ),
    ]
