# Generated by Django 6.0.2 on 2026-02-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0014_roomtypepricingrule_adults_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypepricingrule',
            name='children_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Ako je postavljeno, pravilo vrijedi samo za točan broj djece.', null=True),
        ),
    ]
